### ISSUE TITLE
Behavior of conditional jump

### ISSUE THREAD

**Issue by liuxy600** [boginw/js-y86-64#3]
The [description on wiki page](https://github.com/boginw/js-y86-64/wiki/Instruction-set#table-3-branch-instructions) says `jge` "jumps to Dest if `~(SF^OF)`", but the following code has different behavior with this description.

```
irmovq $0x8000000000000000, %rcx
irmovq $0x2, %rdx
subq %rdx, %rcx

# SF=0, OF=1
jge B2

B1:
irmovq $0xab, %rax
halt

B2:
irmovq $0xcd, %rax
halt
```

**Comment by boginw** [comment]
I'll look into it
